[package]
name = "exctract-id-from-image"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptess = "0.13.4"
tesseract = "0.12.0"
